version: "3.9"
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=jokes_db_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/backend
    command: npm run dev
    restart: always
    depends_on:
      - db
volumes:
  db-data:
    driver: local